//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTour
    {
        public int BookTourID { get; set; }
        public int UserID { get; set; }
        public int TourID { get; set; }
        public Nullable<int> NumberOfAdult { get; set; }
        public Nullable<int> NumberOfChildrent { get; set; }
        public Nullable<float> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string Status { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual User User { get; set; }
    }
}
